#23-04-2026 | 23-04-2026

'''
    Problem:
            Determine the direction of movement between two times on a 24-hour circular clock. 
            The clock wraps around after 23:59 to 00:00, so both forward (clockwise) and backward (counterclockwise).

    Args:
            time1 (str): Starting time in "HH:MM" format.
            time2 (str): Target time in "HH:MM" format.

    Return:
            str: "forward" if clockwise distance is smaller,
                  "backward" if counterclockwise distance is smaller,
                  "equal" if both distances are the same.
'''

def get_direction(time1, time2):
    time1_h, time1_m = map(int,time1.split(":"))
    time2_h, time2_m = map(int,time2.split(":"))

    t1 = time1_h*60 + time1_m
    t2 = time2_h*60 + time2_m

    # generated by ai
    # forward distance on a 24-hour circular clock (wraps around using 1440 minutes in a day)
    forward = (t2 - t1 + 1440) % 1440

    # backward distance on a 24-hour circular clock (reverse direction)
    backward = (t1 - t2 + 1440) % 1440

    if forward < backward:
        return "forward"
    elif forward > backward:
        return "backward"
    else:
        return "equal"
    
def test_cases():
    assert get_direction("10:00", "12:00") == "forward"
    assert get_direction("11:00", "05:00") == "backward"
    assert get_direction("00:00", "12:00") == "equal"
    assert get_direction("15:45", "01:10") == "forward"
    assert get_direction("03:30", "19:50") == "backward"
    assert get_direction("06:30", "18:30") == "equal"
    print("All test cases passed!")

if __name__ == "__main__":
    test_cases()